---

- name: Check node repo is exists
  stat:
    path: "/etc/yum.repos.d/nodesource-el{{ ansible_distribution_major_version }}.repo"
  register: node_repo
  tags: nodejs

- name: Install node dependencies
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - gcc-c++
    - make
  tags: nodejs

- name: Add node repository
  when: not node_repo.stat.exists
  shell: curl -sL https://rpm.nodesource.com/setup_8.x | bash -
  args:
    warn: false
  tags: nodejs

- name: Install node
  yum:
    name: nodejs
    update_cache: yes
  tags: nodejs

- name: Create directory
  file:
    path: ~/.npm-global
    state: directory
    mode: 0755
  become: yes
  become_user: dev
  tags: nodejs

- name: Set npm global path
  shell: npm config set prefix '~/.npm-global'
  args:
    warn: false
  become: yes
  become_user: dev
  tags: nodejs

- name: Add env variable
  template:
    src: nodejs.sh.j2
    dest: /etc/profile.d/nodejs.sh
  tags: nodejs

- name: Reload env
  shell: source /etc/profile
  tags: nodejs
  
