---

- name: Allow PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
  register: sshd_config

- name: Restart sshd
  when: sshd_config.changed
  systemd:
    name: sshd
    daemon_reload: yes
    state: reloaded
