---

- name: Create directory
  file:
    path: /home/dev/.ssh
    state: directory
    mode: 0755

- name: Copy SSH key
  copy:
    src: "{{ item }}"
    dest: /home/dev/.ssh/
    owner: dev
    group: dev
    mode: 0600
    remote_src: no
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: SSH config
  template:
    src: config
    dest: /home/dev/.ssh/config
    owner: dev
    group: dev
    mode: 0644

- name: Clone GitHub repository
  git:
    repo: git@github.com:honpya/demo-aws-sam-dynamodb-local.git
    dest: /home/dev/demo-aws-sam-dynamodb-local
    key_file: /home/dev/.ssh/key
    ssh_opts: "-o StrictHostKeyChecking=no"
