---

- name: Create directory
  file:
    path: /home/dev/.ssh
    state: directory
    owner: dev
    group: dev
    mode: 0755
  tags: github

- name: Copy SSH key
  copy:
    src: "{{ item }}"
    dest: /home/dev/.ssh/
    owner: dev
    group: dev
    mode: 0600
    remote_src: no
  with_fileglob:
    - "{{ role_path }}/files/*"
  tags: github

- name: SSH config
  template:
    src: config
    dest: /home/dev/.ssh/config
    owner: dev
    group: dev
    mode: 0644
  tags: github

- name: Check github repositories exists
  stat:
    path: "/home/dev/{{ github_clone_dir_name }}"
  register: github_repositories_dir

- name: Clone GitHub repository
  when: not github_repositories_dir.stat.exists
  git:
    repo: "{{ github_clone_url }}"
    dest: "/home/dev/{{ github_clone_dir_name }}"
    key_file: "/home/dev/.ssh/{{ github_clone_key_name }}"
    accept_hostkey: yes
    update: no
  become: yes
  become_user: dev
  tags: github
