---

- name: Create directory
  file:
    path: /home/dev/.ssh
    state: directory
    mode: 0755
  tags: github

- name: Copy SSH key
  copy:
    src: "{{ item }}"
    dest: /home/dev/.ssh/
    owner: dev
    group: dev
    mode: 0600
    remote_src: no
  with_fileglob:
    - "{{ role_path }}/files/*"
  tags: github

- name: SSH config
  template:
    src: config
    dest: /home/dev/.ssh/config
    owner: dev
    group: dev
    mode: 0644
  tags: github

- name: Clone GitHub repository
  git:
    repo: "{{ item.url }}"
    dest: "/home/dev/{{ item.dir_name }}"
    key_file: "/home/dev/.ssh/{{ item.key_name }}"
    ssh_opts: "-o StrictHostKeyChecking=no"
  with_items: "{{ github_clone_with_ssh }}"
  tags: github
