---

- hosts: dev
  roles:
    - role: selinux
    - role: timezone
    - role: user
    - role: ssh
    - role: samba
    - role: git
    - role: github
    - role: aws_sam_local
    - role: aws_cli
    - role: aws_dynamodb
